#!/usr/bin/env python3
"""
Visualize GO2 high-level environment layout (target + obstacles) and, optionally,
overlay recorded trajectories from test_reach_avoid.py.
"""

import argparse
import json
from pathlib import Path
from typing import List, Sequence

import matplotlib.pyplot as plt

# obstacle/target config matches GO2HighLevelCfg.rewards_ext
TARGET_POS = (0.0, 0.0)
TARGET_RADIUS = 1.0
OBSTACLE_POSITIONS = [
    (-2.66, -3.66),
    (4.00, -3.00),
    (-3.66, 2.33),
    (3.00, 4.33),
    (0.33, -4.00),
    (-4.33, -0.33),
    (2.66,  0.33),
    (-0.66, 3.33),
    (2.00, 2.00),
    (-2.00, 1.00),
    (5.00, 0.00),
    (2.00, -2.00),
    (-0.5, -2.50),
    (-4.00, -2.00)
]
OBSTACLE_RADIUS = 0.50


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Plot GO2 reach-avoid arena layout plus optional trajectories.")
    parser.add_argument(
        "--traj-file",
        type=str,
        help="JSON log generated by legged_gym/scripts/test_reach_avoid.py.",
    )
    parser.add_argument(
        "--save",
        type=str,
        help="Optional image path. When provided, the figure is saved instead of just showing it.",
    )
    parser.add_argument(
        "--no-show",
        action="store_true",
        help="Skip interactive window (useful when saving to disk).",
    )
    return parser.parse_args()


def load_trajectories(traj_path: Path) -> List[List[Sequence[float]]]:
    with traj_path.open("r", encoding="utf-8") as f:
        payload = json.load(f)
    return payload.get("trajectories", [])


def draw_layout(ax) -> None:
    ax.set_title("GO2 Reach-Avoid Layout (Top View)")
    ax.set_xlabel("X [m]")
    ax.set_ylabel("Y [m]")
    ax.set_aspect("equal", adjustable="box")
    ax.set_xlim(-6, 6)
    ax.set_ylim(-6, 6)
    ax.grid(True, linestyle="--", alpha=0.4)

    for idx, (x, y) in enumerate(OBSTACLE_POSITIONS, start=1):
        circle = plt.Circle((x, y), OBSTACLE_RADIUS, color="red", alpha=0.35, edgecolor="darkred")
        ax.add_patch(circle)
        ax.text(x, y, f"H{idx}", color="darkred", ha="center", va="center", fontsize=8)

    target_circle = plt.Circle(TARGET_POS, TARGET_RADIUS, color="green", alpha=0.35, edgecolor="darkgreen")
    ax.add_patch(target_circle)
    ax.text(
        TARGET_POS[0],
        TARGET_POS[1],
        "Target",
        color="darkgreen",
        ha="center",
        va="center",
        fontsize=9,
        fontweight="bold",
    )


def overlay_trajectories(ax, trajectories: List[List[Sequence[float]]]) -> None:
    if not trajectories:
        return
    cmap = plt.cm.get_cmap("tab10", max(1, len(trajectories)))
    for idx, traj in enumerate(trajectories, start=1):
        if len(traj) < 2:
            continue
        xs = [p[0] for p in traj]
        ys = [p[1] for p in traj]
        color = cmap((idx - 1) % cmap.N)
        ax.plot(xs, ys, color=color, linewidth=1.5, alpha=0.85)
        ax.scatter(xs[0], ys[0], color=color, marker="o", s=25)
        ax.scatter(xs[-1], ys[-1], color=color, marker="x", s=30)


def main() -> None:
    args = parse_args()
    fig, ax = plt.subplots(figsize=(6, 6))
    draw_layout(ax)

    if args.traj_file:
        traj_path = Path(args.traj_file).expanduser()
        if traj_path.exists():
            trajectories = load_trajectories(traj_path)
            overlay_trajectories(ax, trajectories)
            print(f"Loaded {len(trajectories)} trajectories from {traj_path}")
        else:
            print(f"[WARN] Trajectory file not found: {traj_path}")

    plt.tight_layout()
    if args.save:
        out_path = Path(args.save).expanduser()
        out_path.parent.mkdir(parents=True, exist_ok=True)
        fig.savefig(out_path, dpi=300)
        print(f"Saved figure to {out_path}")
    if not args.no_show:
        plt.show()


if __name__ == "__main__":
    main()
